FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY container-publish .

LABEL org.opencontainers.image.source="https://github.com/joshua-montgomery-1/fortnite-sprite-tracker"
LABEL org.opencontainers.image.title="Fortnite Sprite Tracker"
LABEL org.opencontainers.image.description="Sprite Scout Blazor Web App"

ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080

USER $APP_UID
ENTRYPOINT ["dotnet", "FortniteSpriteTracker.dll"]
