// <auto-generated />
using System;
using FortniteSpriteTracker.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FortniteSpriteTracker.DataAccess.Data.Migrations
{
    [DbContext(typeof(SpriteTrackerDbContext))]
    partial class SpriteTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Chapter")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Chapter", "Number")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SeasonSpriteFamily", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SpriteFamilyId")
                        .HasColumnType("integer");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("RarityColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("SeasonId", "SpriteFamilyId");

                    b.HasIndex("SpriteFamilyId");

                    b.HasIndex("SeasonId", "DisplayOrder");

                    b.ToTable("SeasonSpriteFamilies");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SeasonSpriteVariant", b =>
                {
                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<int>("SpriteVariantId")
                        .HasColumnType("integer");

                    b.HasKey("SeasonId", "SpriteVariantId");

                    b.HasIndex("SpriteVariantId");

                    b.ToTable("SeasonSpriteVariants");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("SpriteFamilies");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteProgress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("SpriteVariantId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMastered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "SpriteVariantId");

                    b.HasIndex("SpriteVariantId");

                    b.ToTable("SpriteProgress");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SpriteFamilyId")
                        .HasColumnType("integer");

                    b.Property<int>("VariantStyleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VariantStyleId");

                    b.HasIndex("SpriteFamilyId", "VariantStyleId")
                        .IsUnique();

                    b.ToTable("SpriteVariants");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EpicDisplayName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsCollectionPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEpicDisplayName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("NormalizedEpicDisplayName");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.VariantStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageSuffix")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VariantStyles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SeasonSpriteFamily", b =>
                {
                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.Season", "Season")
                        .WithMany("SpriteFamilies")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.SpriteFamily", "SpriteFamily")
                        .WithMany("Seasons")
                        .HasForeignKey("SpriteFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("SpriteFamily");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SeasonSpriteVariant", b =>
                {
                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.Season", "Season")
                        .WithMany("SpriteVariants")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", "SpriteVariant")
                        .WithMany("Seasons")
                        .HasForeignKey("SpriteVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("SpriteVariant");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteProgress", b =>
                {
                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", "SpriteVariant")
                        .WithMany("Progress")
                        .HasForeignKey("SpriteVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.UserAccount", "User")
                        .WithMany("SpriteProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpriteVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", b =>
                {
                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.SpriteFamily", "SpriteFamily")
                        .WithMany("Variants")
                        .HasForeignKey("SpriteFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.VariantStyle", "VariantStyle")
                        .WithMany("Variants")
                        .HasForeignKey("VariantStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpriteFamily");

                    b.Navigation("VariantStyle");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.Season", b =>
                {
                    b.Navigation("SpriteFamilies");

                    b.Navigation("SpriteVariants");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteFamily", b =>
                {
                    b.Navigation("Seasons");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", b =>
                {
                    b.Navigation("Progress");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.UserAccount", b =>
                {
                    b.Navigation("SpriteProgress");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.VariantStyle", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
