// <auto-generated />
using System;
using FortniteSpriteTracker.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FortniteSpriteTracker.DataAccess.Migrations
{
    [DbContext(typeof(SpriteTrackerDbContext))]
    partial class SpriteTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Chapter")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Chapter", "Number")
                        .IsUnique();

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chapter = 7,
                            Name = "Chapter 7 · Season 3",
                            Number = 3
                        });
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.Sprite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SeasonId", "Name")
                        .IsUnique();

                    b.ToTable("Sprites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ability = "Replenishes shields for you and nearby squadmates while in water.",
                            Name = "Water",
                            Rarity = "Rare",
                            SeasonId = 1,
                            Slug = "water"
                        },
                        new
                        {
                            Id = 2,
                            Ability = "May reveal extra rare items when you open chests.",
                            Name = "Earth",
                            Rarity = "Rare",
                            SeasonId = 1,
                            Slug = "earth"
                        },
                        new
                        {
                            Id = 3,
                            Ability = "Releases a fiery burst after you deal enough damage.",
                            Name = "Fire",
                            Rarity = "Rare",
                            SeasonId = 1,
                            Slug = "fire"
                        },
                        new
                        {
                            Id = 4,
                            Ability = "Increases swim speed and boosts movement while under fire.",
                            Name = "Fishy",
                            Rarity = "Rare",
                            SeasonId = 1,
                            Slug = "fishy"
                        },
                        new
                        {
                            Id = 5,
                            Ability = "Increases sprint speed and jump height while equipped.",
                            Name = "Air",
                            Rarity = "Rare",
                            SeasonId = 1,
                            Slug = "air"
                        },
                        new
                        {
                            Id = 6,
                            Ability = "Emoting and jamming replenish your shields.",
                            Name = "Duck",
                            Rarity = "Epic",
                            SeasonId = 1,
                            Slug = "duck"
                        },
                        new
                        {
                            Id = 7,
                            Ability = "Briefly cloaks you whenever you reload.",
                            Name = "Ghost",
                            Rarity = "Epic",
                            SeasonId = 1,
                            Slug = "ghost"
                        },
                        new
                        {
                            Id = 8,
                            Ability = "Siphons health and shields after eliminations.",
                            Name = "Demon",
                            Rarity = "Epic",
                            SeasonId = 1,
                            Slug = "demon"
                        },
                        new
                        {
                            Id = 9,
                            Ability = "Makes your pickaxe deal significantly more damage.",
                            Name = "King",
                            Rarity = "Epic",
                            SeasonId = 1,
                            Slug = "king"
                        },
                        new
                        {
                            Id = 10,
                            Ability = "Grants a Shock Rock charge after enough damage.",
                            Name = "Aura",
                            Rarity = "Epic",
                            SeasonId = 1,
                            Slug = "drifter"
                        },
                        new
                        {
                            Id = 11,
                            Ability = "Traversal actions trigger speed, reload, and fire-rate Overdrive.",
                            Name = "Striker",
                            Rarity = "Epic",
                            SeasonId = 1,
                            Slug = "soccer"
                        },
                        new
                        {
                            Id = 12,
                            Ability = "Grants random loot each level and Legendary loot at max level.",
                            Name = "Dream",
                            Rarity = "Legendary",
                            SeasonId = 1,
                            Slug = "dream"
                        },
                        new
                        {
                            Id = 13,
                            Ability = "Can grant a short infinite-ammo effect at max mastery.",
                            Name = "Punk",
                            Rarity = "Legendary",
                            SeasonId = 1,
                            Slug = "punk"
                        },
                        new
                        {
                            Id = 14,
                            Ability = "Boosts your maximum Health and Shield while equipped.",
                            Name = "Boss",
                            Rarity = "Legendary",
                            SeasonId = 1,
                            Slug = "boss"
                        },
                        new
                        {
                            Id = 15,
                            Ability = "Reveals enemy foot trails for you and nearby squadmates.",
                            Name = "Seven",
                            Rarity = "Legendary",
                            SeasonId = 1,
                            Slug = "seven"
                        },
                        new
                        {
                            Id = 16,
                            Ability = "Opening Ammo Boxes has a chance to upgrade your weapon.",
                            Name = "Llama",
                            Rarity = "Legendary",
                            SeasonId = 1,
                            Slug = "llama"
                        },
                        new
                        {
                            Id = 17,
                            Ability = "Marks nearby rare Sprites or enemies carrying them - and you.",
                            Name = "Peely",
                            Rarity = "Legendary",
                            SeasonId = 1,
                            Slug = "peely"
                        },
                        new
                        {
                            Id = 18,
                            Ability = "Marks players who damage you and reveals their location.",
                            Name = "Grim Reaper",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "grimreaper"
                        },
                        new
                        {
                            Id = 19,
                            Ability = "Creates a Shield Bubble Jr. whenever you heal.",
                            Name = "Zero Point",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "zeropoint"
                        },
                        new
                        {
                            Id = 20,
                            Ability = "May award extra or Mythic loot after eliminations.",
                            Name = "Burnt Peanut",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "theburntpeanut"
                        },
                        new
                        {
                            Id = 21,
                            Ability = "Deploy the Bat Cape midair and improve rare-Sprite chest finds.",
                            Name = "Batman",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "batman"
                        },
                        new
                        {
                            Id = 22,
                            Ability = "Replenishes nearby shields after an elimination.",
                            Name = "Pollo",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "pollo"
                        },
                        new
                        {
                            Id = 23,
                            Ability = "Empowers destructive slides and boosts combat after slide-kicks.",
                            Name = "Vini Jr.",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "vinijr"
                        },
                        new
                        {
                            Id = 24,
                            Ability = "Knocks and eliminations briefly reveal nearby enemies.",
                            Name = "John Wick",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "johnwick"
                        },
                        new
                        {
                            Id = 25,
                            Ability = "Regenerates low health with Cloak and low gravity.",
                            Name = "Ironmouse",
                            Rarity = "Mythic",
                            SeasonId = 1,
                            Slug = "ironmouse"
                        });
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpriteVariantId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMastered")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "SpriteVariantId");

                    b.HasIndex("SpriteVariantId");

                    b.ToTable("SpriteProgress");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("SpriteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpriteId", "Name")
                        .IsUnique();

                    b.ToTable("SpriteVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "images/sprites/water_basic.webp",
                            Name = "Normal",
                            SpriteId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "images/sprites/water_gold.webp",
                            Name = "Gold",
                            SpriteId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "images/sprites/water_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "images/sprites/water_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "images/sprites/water_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "images/sprites/water_quack.webp",
                            Name = "Quack",
                            SpriteId = 1
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "images/sprites/water_gem.webp",
                            Name = "Gem",
                            SpriteId = 1
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "images/sprites/earth_basic.webp",
                            Name = "Normal",
                            SpriteId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "images/sprites/earth_gold.webp",
                            Name = "Gold",
                            SpriteId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "images/sprites/earth_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 2
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "images/sprites/earth_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 2
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "images/sprites/earth_cube.webp",
                            Name = "Cube",
                            SpriteId = 2
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "images/sprites/earth_quack.webp",
                            Name = "Quack",
                            SpriteId = 2
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "images/sprites/earth_gem.webp",
                            Name = "Gem",
                            SpriteId = 2
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "images/sprites/fire_basic.webp",
                            Name = "Normal",
                            SpriteId = 3
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "images/sprites/fire_gold.webp",
                            Name = "Gold",
                            SpriteId = 3
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "images/sprites/fire_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 3
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "images/sprites/fire_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 3
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "images/sprites/fire_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 3
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "images/sprites/fire_cube.webp",
                            Name = "Cube",
                            SpriteId = 3
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "images/sprites/fire_quack.webp",
                            Name = "Quack",
                            SpriteId = 3
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "images/sprites/fishy_basic.webp",
                            Name = "Normal",
                            SpriteId = 4
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "images/sprites/fishy_gold.webp",
                            Name = "Gold",
                            SpriteId = 4
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "images/sprites/fishy_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 4
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "images/sprites/fishy_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 4
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "images/sprites/fishy_cube.webp",
                            Name = "Cube",
                            SpriteId = 4
                        },
                        new
                        {
                            Id = 27,
                            ImagePath = "images/sprites/air_basic.webp",
                            Name = "Normal",
                            SpriteId = 5
                        },
                        new
                        {
                            Id = 28,
                            ImagePath = "images/sprites/air_gold.webp",
                            Name = "Gold",
                            SpriteId = 5
                        },
                        new
                        {
                            Id = 29,
                            ImagePath = "images/sprites/air_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 5
                        },
                        new
                        {
                            Id = 30,
                            ImagePath = "images/sprites/air_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 5
                        },
                        new
                        {
                            Id = 31,
                            ImagePath = "images/sprites/air_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 5
                        },
                        new
                        {
                            Id = 32,
                            ImagePath = "images/sprites/duck_basic.webp",
                            Name = "Normal",
                            SpriteId = 6
                        },
                        new
                        {
                            Id = 33,
                            ImagePath = "images/sprites/duck_gold.webp",
                            Name = "Gold",
                            SpriteId = 6
                        },
                        new
                        {
                            Id = 34,
                            ImagePath = "images/sprites/duck_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 6
                        },
                        new
                        {
                            Id = 35,
                            ImagePath = "images/sprites/duck_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 6
                        },
                        new
                        {
                            Id = 36,
                            ImagePath = "images/sprites/duck_gem.webp",
                            Name = "Gem",
                            SpriteId = 6
                        },
                        new
                        {
                            Id = 37,
                            ImagePath = "images/sprites/ghost_basic.webp",
                            Name = "Normal",
                            SpriteId = 7
                        },
                        new
                        {
                            Id = 38,
                            ImagePath = "images/sprites/ghost_gold.webp",
                            Name = "Gold",
                            SpriteId = 7
                        },
                        new
                        {
                            Id = 39,
                            ImagePath = "images/sprites/ghost_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 7
                        },
                        new
                        {
                            Id = 40,
                            ImagePath = "images/sprites/ghost_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 7
                        },
                        new
                        {
                            Id = 41,
                            ImagePath = "images/sprites/ghost_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 7
                        },
                        new
                        {
                            Id = 42,
                            ImagePath = "images/sprites/demon_basic.webp",
                            Name = "Normal",
                            SpriteId = 8
                        },
                        new
                        {
                            Id = 43,
                            ImagePath = "images/sprites/demon_gold.webp",
                            Name = "Gold",
                            SpriteId = 8
                        },
                        new
                        {
                            Id = 44,
                            ImagePath = "images/sprites/demon_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 8
                        },
                        new
                        {
                            Id = 45,
                            ImagePath = "images/sprites/demon_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 8
                        },
                        new
                        {
                            Id = 46,
                            ImagePath = "images/sprites/demon_gem.webp",
                            Name = "Gem",
                            SpriteId = 8
                        },
                        new
                        {
                            Id = 47,
                            ImagePath = "images/sprites/king_basic.webp",
                            Name = "Normal",
                            SpriteId = 9
                        },
                        new
                        {
                            Id = 48,
                            ImagePath = "images/sprites/king_gold.webp",
                            Name = "Gold",
                            SpriteId = 9
                        },
                        new
                        {
                            Id = 49,
                            ImagePath = "images/sprites/king_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 9
                        },
                        new
                        {
                            Id = 50,
                            ImagePath = "images/sprites/king_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 9
                        },
                        new
                        {
                            Id = 51,
                            ImagePath = "images/sprites/king_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 9
                        },
                        new
                        {
                            Id = 52,
                            ImagePath = "images/sprites/drifter_basic.webp",
                            Name = "Normal",
                            SpriteId = 10
                        },
                        new
                        {
                            Id = 53,
                            ImagePath = "images/sprites/drifter_gold.webp",
                            Name = "Gold",
                            SpriteId = 10
                        },
                        new
                        {
                            Id = 54,
                            ImagePath = "images/sprites/drifter_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 10
                        },
                        new
                        {
                            Id = 55,
                            ImagePath = "images/sprites/drifter_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 10
                        },
                        new
                        {
                            Id = 56,
                            ImagePath = "images/sprites/drifter_gem.webp",
                            Name = "Gem",
                            SpriteId = 10
                        },
                        new
                        {
                            Id = 57,
                            ImagePath = "images/sprites/soccer_basic.webp",
                            Name = "Normal",
                            SpriteId = 11
                        },
                        new
                        {
                            Id = 58,
                            ImagePath = "images/sprites/soccer_gold.webp",
                            Name = "Gold",
                            SpriteId = 11
                        },
                        new
                        {
                            Id = 59,
                            ImagePath = "images/sprites/soccer_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 11
                        },
                        new
                        {
                            Id = 60,
                            ImagePath = "images/sprites/soccer_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 11
                        },
                        new
                        {
                            Id = 61,
                            ImagePath = "images/sprites/soccer_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 11
                        },
                        new
                        {
                            Id = 62,
                            ImagePath = "images/sprites/dream_basic.webp",
                            Name = "Normal",
                            SpriteId = 12
                        },
                        new
                        {
                            Id = 63,
                            ImagePath = "images/sprites/dream_gold.webp",
                            Name = "Gold",
                            SpriteId = 12
                        },
                        new
                        {
                            Id = 64,
                            ImagePath = "images/sprites/dream_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 12
                        },
                        new
                        {
                            Id = 65,
                            ImagePath = "images/sprites/dream_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 12
                        },
                        new
                        {
                            Id = 66,
                            ImagePath = "images/sprites/dream_cube.webp",
                            Name = "Cube",
                            SpriteId = 12
                        },
                        new
                        {
                            Id = 67,
                            ImagePath = "images/sprites/punk_basic.webp",
                            Name = "Normal",
                            SpriteId = 13
                        },
                        new
                        {
                            Id = 68,
                            ImagePath = "images/sprites/punk_gold.webp",
                            Name = "Gold",
                            SpriteId = 13
                        },
                        new
                        {
                            Id = 69,
                            ImagePath = "images/sprites/punk_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 13
                        },
                        new
                        {
                            Id = 70,
                            ImagePath = "images/sprites/punk_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 13
                        },
                        new
                        {
                            Id = 71,
                            ImagePath = "images/sprites/punk_cube.webp",
                            Name = "Cube",
                            SpriteId = 13
                        },
                        new
                        {
                            Id = 72,
                            ImagePath = "images/sprites/boss_basic.webp",
                            Name = "Normal",
                            SpriteId = 14
                        },
                        new
                        {
                            Id = 73,
                            ImagePath = "images/sprites/boss_gold.webp",
                            Name = "Gold",
                            SpriteId = 14
                        },
                        new
                        {
                            Id = 74,
                            ImagePath = "images/sprites/boss_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 14
                        },
                        new
                        {
                            Id = 75,
                            ImagePath = "images/sprites/boss_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 14
                        },
                        new
                        {
                            Id = 76,
                            ImagePath = "images/sprites/boss_cube.webp",
                            Name = "Cube",
                            SpriteId = 14
                        },
                        new
                        {
                            Id = 77,
                            ImagePath = "images/sprites/seven_basic.webp",
                            Name = "Normal",
                            SpriteId = 15
                        },
                        new
                        {
                            Id = 78,
                            ImagePath = "images/sprites/seven_gold.webp",
                            Name = "Gold",
                            SpriteId = 15
                        },
                        new
                        {
                            Id = 79,
                            ImagePath = "images/sprites/seven_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 15
                        },
                        new
                        {
                            Id = 80,
                            ImagePath = "images/sprites/seven_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 15
                        },
                        new
                        {
                            Id = 81,
                            ImagePath = "images/sprites/seven_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 15
                        },
                        new
                        {
                            Id = 82,
                            ImagePath = "images/sprites/llama_basic.webp",
                            Name = "Normal",
                            SpriteId = 16
                        },
                        new
                        {
                            Id = 83,
                            ImagePath = "images/sprites/llama_gold.webp",
                            Name = "Gold",
                            SpriteId = 16
                        },
                        new
                        {
                            Id = 84,
                            ImagePath = "images/sprites/llama_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 16
                        },
                        new
                        {
                            Id = 85,
                            ImagePath = "images/sprites/llama_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 16
                        },
                        new
                        {
                            Id = 86,
                            ImagePath = "images/sprites/llama_gem.webp",
                            Name = "Gem",
                            SpriteId = 16
                        },
                        new
                        {
                            Id = 87,
                            ImagePath = "images/sprites/peely_basic.webp",
                            Name = "Normal",
                            SpriteId = 17
                        },
                        new
                        {
                            Id = 88,
                            ImagePath = "images/sprites/peely_gold.webp",
                            Name = "Gold",
                            SpriteId = 17
                        },
                        new
                        {
                            Id = 89,
                            ImagePath = "images/sprites/peely_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 17
                        },
                        new
                        {
                            Id = 90,
                            ImagePath = "images/sprites/peely_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 17
                        },
                        new
                        {
                            Id = 91,
                            ImagePath = "images/sprites/peely_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 17
                        },
                        new
                        {
                            Id = 92,
                            ImagePath = "images/sprites/grimreaper_basic.webp",
                            Name = "Normal",
                            SpriteId = 18
                        },
                        new
                        {
                            Id = 93,
                            ImagePath = "images/sprites/grimreaper_gold.webp",
                            Name = "Gold",
                            SpriteId = 18
                        },
                        new
                        {
                            Id = 94,
                            ImagePath = "images/sprites/grimreaper_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 18
                        },
                        new
                        {
                            Id = 95,
                            ImagePath = "images/sprites/grimreaper_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 18
                        },
                        new
                        {
                            Id = 96,
                            ImagePath = "images/sprites/grimreaper_cube.webp",
                            Name = "Cube",
                            SpriteId = 18
                        },
                        new
                        {
                            Id = 97,
                            ImagePath = "images/sprites/grimreaper_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 18
                        },
                        new
                        {
                            Id = 98,
                            ImagePath = "images/sprites/grimreaper_gem.webp",
                            Name = "Gem",
                            SpriteId = 18
                        },
                        new
                        {
                            Id = 99,
                            ImagePath = "images/sprites/zeropoint_basic.webp",
                            Name = "Normal",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 100,
                            ImagePath = "images/sprites/zeropoint_gold.webp",
                            Name = "Gold",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 101,
                            ImagePath = "images/sprites/zeropoint_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 102,
                            ImagePath = "images/sprites/zeropoint_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 103,
                            ImagePath = "images/sprites/zeropoint_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 104,
                            ImagePath = "images/sprites/zeropoint_cube.webp",
                            Name = "Cube",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 105,
                            ImagePath = "images/sprites/zeropoint_quack.webp",
                            Name = "Quack",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 106,
                            ImagePath = "images/sprites/zeropoint_gem.webp",
                            Name = "Gem",
                            SpriteId = 19
                        },
                        new
                        {
                            Id = 107,
                            ImagePath = "images/sprites/theburntpeanut_basic.webp",
                            Name = "Normal",
                            SpriteId = 20
                        },
                        new
                        {
                            Id = 108,
                            ImagePath = "images/sprites/batman_basic.webp",
                            Name = "Normal",
                            SpriteId = 21
                        },
                        new
                        {
                            Id = 109,
                            ImagePath = "images/sprites/batman_gold.webp",
                            Name = "Gold",
                            SpriteId = 21
                        },
                        new
                        {
                            Id = 110,
                            ImagePath = "images/sprites/batman_gummy.webp",
                            Name = "Gummy",
                            SpriteId = 21
                        },
                        new
                        {
                            Id = 111,
                            ImagePath = "images/sprites/batman_galaxy.webp",
                            Name = "Galaxy",
                            SpriteId = 21
                        },
                        new
                        {
                            Id = 112,
                            ImagePath = "images/sprites/batman_holofoil.webp",
                            Name = "Holofoil",
                            SpriteId = 21
                        },
                        new
                        {
                            Id = 113,
                            ImagePath = "images/sprites/batman_cube.webp",
                            Name = "Cube",
                            SpriteId = 21
                        },
                        new
                        {
                            Id = 114,
                            ImagePath = "images/sprites/pollo_basic.webp",
                            Name = "Normal",
                            SpriteId = 22
                        },
                        new
                        {
                            Id = 115,
                            ImagePath = "images/sprites/vinijr_basic.webp",
                            Name = "Normal",
                            SpriteId = 23
                        },
                        new
                        {
                            Id = 116,
                            ImagePath = "images/sprites/johnwick_basic.webp",
                            Name = "Normal",
                            SpriteId = 24
                        },
                        new
                        {
                            Id = 117,
                            ImagePath = "images/sprites/ironmouse_basic.webp",
                            Name = "Normal",
                            SpriteId = 25
                        });
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCollectionPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EpicDisplayName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NormalizedEpicDisplayName")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("NormalizedEpicDisplayName");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.Sprite", b =>
                {
                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.Season", "Season")
                        .WithMany("Sprites")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteProgress", b =>
                {
                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", "SpriteVariant")
                        .WithMany("Progress")
                        .HasForeignKey("SpriteVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.UserAccount", "User")
                        .WithMany("SpriteProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpriteVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", b =>
                {
                    b.HasOne("FortniteSpriteTracker.DataAccess.Entities.Sprite", "Sprite")
                        .WithMany("Variants")
                        .HasForeignKey("SpriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprite");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.Season", b =>
                {
                    b.Navigation("Sprites");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.Sprite", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.SpriteVariant", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("FortniteSpriteTracker.DataAccess.Entities.UserAccount", b =>
                {
                    b.Navigation("SpriteProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
